#!/bin/bash -f
#currentwindow=`tmux list-window | tr '\t' ' ' | sed -n -e '/(active)/s/^[^:]*: *\([^ ]*\) .*/\1/gp'`;
currentwindow=`tmux list-window | tr '\t' ' ' | tr -d '*' | sed -n -e '/(active)/s/^[^:]*: *\([^ ]*\) .*/\1/gp'`;
currentpane=`tmux list-panes | sed -n -e '/(active)/s/^\([^:]*\):.*/\1/gp'`;
panecount=`tmux list-panes | wc | sed -e 's/^ *//g' -e 's/ .*$//g'`;
inzoom=`echo $currentwindow | sed -n -e '/^zoom/p'`;
if [ $panecount -ne 1 ]; then
    inzoom="";
fi

if [ $inzoom ]; then
    lastpane=`echo $currentwindow | rev | cut -f 1 -d '@' | rev`;
    lastwindow=`echo $currentwindow | cut -f 2- -d '@' | rev | cut -f 2- -d '@' | rev`;
    tmux select-window -t $lastwindow;
    tmux select-pane -t $lastpane;
    tmux swap-pane -s $currentwindow;
    tmux kill-window -t $currentwindow;
else
    alreadyzoomed=`tmux list-window | grep -F $currentwindow@$currentpane | wc -l`;

    if [ $alreadyzoomed -ne 0 ]; then
        tmux send-keys "zoom@$currentwindow@*$currentpane";
        tmux swap-pane -s "zoom@$currentwindow@*$currentpane";
        tmux kill-window -t "zoom@$currentwindow@*$currentpane";
    else 
        newwindowname=zoom@$currentwindow@$currentpane;
        tmux new-window -d -n $newwindowname;
        tmux swap-pane -s $newwindowname;
        tmux send-keys 'PS1=' C-m 'for i in {1..5000}' C-m 'do echo -n "# "' C-m 'done' C-m ' ZOOMED OUT # # # # '
        tmux select-window -t $newwindowname;
    fi
fi

